### ISSUE TITLE
   java.lang.AssertionError: illegal type variable reference 

### ISSUE THREAD

**Issue by hirenpatel868** [yehiahd/FastSave-Android#6]
` java.lang.AssertionError: illegal type variable reference
        at libcore.reflect.TypeVariableImpl.resolve(TypeVariableImpl.java:111)
        at libcore.reflect.TypeVariableImpl.getGenericDeclaration(TypeVariableImpl.java:125)
        at com.google.common.reflect.TypeResolver$TypeVariableKey.equalsTypeVariable(SourceFile:601)
        at com.google.common.reflect.TypeResolver$TypeVariableKey.equals(SourceFile:568)
        at com.google.common.collect.RegularImmutableMap.a(SourceFile:146)
        at com.google.common.collect.RegularImmutableMap.get(SourceFile:134)
        at com.google.common.reflect.TypeResolver$TypeTable.resolveInternal(SourceFile:326)
        at com.google.common.reflect.TypeResolver$TypeTable.a(SourceFile:314)
        at com.google.common.reflect.TypeResolver.resolveType(SourceFile:218)
        at com.google.common.reflect.TypeResolver.resolveTypes(SourceFile:241)
        at com.google.common.reflect.TypeResolver.resolveParameterizedType(SourceFile:264)
        at com.google.common.reflect.TypeResolver.resolveType(SourceFile:220)
        at com.google.common.reflect.TypeToken.where(SourceFile:231)
        at com.google.common.reflect.TypeToken.where(SourceFile:253)
        at com.appizona.yehiahd.fastsave.FastSave.getObjectsList`

**Comment by yehiahd** [comment]
@hirenpatel868 
On which phones do you have this issue?
Which Android, Android Studio and Gradle Plug-in Versions

**Comment by yehiahd** [comment]
Thanks for your feedback. Actually i figured out the problem and now its solved in the latest version
please use implementation 'com.github.yehiahd:FastSave-Android:1.0.6'.
